<?php
 function payment_field_widget_info(){
    return array(
      'payment' => array(
       'label' => t('Payment'),
      'field types' => array('number_float','number_integer'),
      'settings' => array(
        'size' => 100 ,
       ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
      )),
    );
  }
function payment_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items,$delta, $element) {

  $element['cardnumber']=array(
    '#type' => 'textfield',
    '#maxlength' => 16,
    '#title' => t('Payment'),

    '#element_validate' => array('payment_field_widget_validate'),
    '#ajax' => array(
    'callback' => '_payment_field_widget_form_callback',
    'wrapper' => 'payment-field-widget-form-wrapper',

    ),

  );
  $element['cardtype'] = array(
  '#type' => 'item',
  '#markup' => '<div id="payment-field-widget-form-wrapper"></div>',
  '#description' => t("You enerted "),
  '#element_validate' => array('payment_field_widget_validate'),
  ); 
 /* $element['Name'] = array(
'#type' => 'textfield',
'#title' => t('Name'),
'#description' => $form, 
  );*/
 if ($element['cardnumber'] == "/^4[0-9]{12}(?:[0-9]{3})?$/") 
    {
      $form['cardnumber']['new_item'] = array(
      '#type' => 'textfield',
      'default_value' => 'VISA',
    );
    }

  
return array(
'value'=>$element,
);

}
function _payment_field_widget_form_callback($form, &$form_state){
   echo "<pre>" .print_r($form,"\n"). "</pre>";
     if ($form['cardnumber'] == "/^4[0-9]{12}(?:[0-9]{3})?$/") 
    {
      $form['cardnumber']['new_item'] = array(
      '#type' => 'textfield',
      'default_value' => 'VISA',
    );
    }
return $form;
 
  $field_name = $element['#value'];
      $value = $element['#value'];
    $cardtype = array(
        "visa"       => "/^4[0-9]{12}(?:[0-9]{3})?$/",
        "mastercard" => "/^5[1-5][0-9]{14}$/",
        "amex"       => "/^3[47][0-9]{13}$/",
        "discover"   => "/^6(?:011|5[0-9]{2})[0-9]{12}$/",
    ); 
    if (preg_match($cardtype['visa'],$value))
    {
      $type= "visa";
        return true;
    }
    else if (preg_match($cardtype['mastercard'],$value))
    {
    $type= "Mastercard";
 return true;
    }
    else if (preg_match($cardtype['amex'],$value))
    {
     $type= "amex";
 return true;
    }
    else if (preg_match($cardtype['discover'],$value))
    {
      $type= "discover";
  return true;
    }
    else
    {
      form_error($element, t('invalid Debit or Credit card.'));
    } 
}

function payment_field_widget_validate($element,  $form) {
   
}
