<?php
/**
 * Implements hook_node_info()
 */
function productcustomtype_node_info() {
    return array(
        'product' => array(
            'name' => t('Product'),
            'base' => 'product',
            'description' => t('You can add new Products here'),
            'has_title' => TRUE,
            'title_label' => t('Product Name')

        )
        
    );
    
}


function product_form($node, $form_state) {
    return node_content_form($node, $form_state);
  }




